### ISSUE TITLE
Not possile to make facedancer21 build

### ISSUE THREAD

**Issue by Quicktimer** [travisgoodspeed/goodfet#37]
Hello all,

I`m trying to make a build for the facedancer21 board. Everything from this page is done (https://ericeastwood.com/blog/15/facedancer21-getting-started-in-windows) but an error occurs when I try to make a build.  
Do you know what is the issue an how can be fixed?
Can anybody make for me a facedance21 build?

Thanks.
Best regards! 
![image](https://user-images.githubusercontent.com/20852948/35901766-ff88d85a-0be0-11e8-8a5a-05119fc75368.png)

**Comment by travisgoodspeed** [comment]
This is not a support forum, and this code was never designed to compile natively on Windows.

You might get away with running `make install`, as this problem is called by the Windows shell not expanding wildcards.  A better choice might be Windows Services for Linux, which can run a proper unix environment.

Cheers from Pizza Rat City,
-Travis
